language: c
compiler:
  - gcc
    
branches:
  only:
  - /.*/
    
addons:
  sonarcloud:
    organization: "joaliasbarb"
    token: ${SONAR_TOKEN}
        
env:
  global:
    - BUILD_TYPE=Release
     
install:       
  # Install latest cmake
  - |
      CMAKE_URL="https://cmake.org/files/v3.20/cmake-3.20.5-linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${PWD}/cmake/bin:${PATH}
  - cmake --version
      
script:
  - mkdir -p build
  - cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/ --config ${BUILD_TYPE}
  - cd build/ && ctest -C ${BUILD_TYPE} && cd ..
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
  
cache:
  directories:
    - '$HOME/.sonar/cache'